extends: ["spectral:oas"]

rules:
  operation-operationId: error
  operation-description: warn
  operation-tags: warn
  info-contact: warn
  info-description: warn
  tag-description: warn
  typed-enum: warn
  no-$ref-siblings: error
  operation-success-response: error
